<?php

namespace App\Support\Documents\LoanAgreement;

class LoanAgreementTemplateSchema
{
    public static function make(): array
    {
        return [
            'document_type' => 'loan_agreement',
            'renderer' => 'gemini_pdf_html',
            'source_format' => 'pdf',
            'preserve' => [
                'title_page',
                'party_order',
                'clause_numbering',
                'schedule_structure',
                'signature_structure',
            ],
            'variables' => [
                'agreement_date',
                'lender_entity_type',
                'lender_full_name',
                'lender_address',
                'lender_company_name',
                'lender_company_number',
                'lender_registered_office_address',
                'lender_signatory_name',
                'borrower_entity_type',
                'borrower_full_name',
                'borrower_address',
                'borrower_company_name',
                'borrower_company_number',
                'borrower_registered_office_address',
                'borrower_signatory_name',
                'loan_amount_gbp',
                'secured_or_unsecured',
                'drawdown_method',
                'loan_term_months',
                'repayment_terms',
                'repayment_bank_account_type',
                'loan_purpose',
                'loan_purpose_property_related',
                'property_project_type',
                'property_control_information_level',
                'property_restriction_occupy',
                'property_restriction_third_party_interest',
                'property_restriction_renting',
                'interest_structure',
                'interest_rate_value',
                'interest_payment_timing',
                'fixed_interest_amount',
                'default_interest_rate',
                'lender_assignment_allowed',
                'borrower_assignment_allowed',
                'jurisdiction_exclusive',
                'jurisdiction_requested_location',
                'security_types',
                'first_charge_property_address',
                'first_charge_title_number',
                'second_charge_property_address',
                'second_charge_title_number',
                'personal_guarantor_details',
                'personal_guarantor_connection',
                'multiple_borrowers',
                'additional_borrower_details',
                'borrower_company_operations_info_required',
                'company_info_audited_accounts',
                'company_info_monthly_management_accounts',
                'company_info_notices_to_shareholders_creditors',
                'company_info_other_reasonable_requests',
                'upsell_board_resolutions',
                'upsell_shareholder_resolution',
                'bankruptcy_search_requested',
                'additional_company_info_required',
                'anything_else',
            ],
            'derived_flags' => [
                'has_property_security',
                'has_first_charge',
                'has_second_charge',
                'has_debenture',
                'has_personal_guarantee',
                'borrower_is_company',
                'lender_is_company',
                'has_multiple_borrowers',
                'is_staged_drawdown',
                'is_property_development',
                'is_overseas_repayment',
                'interest_is_fixed_sum',
                'interest_is_yearly',
                'interest_is_monthly',
                'interest_is_rolled_up_compound',
                'interest_is_rolled_up_simple',
                'jurisdiction_is_exclusive',
            ],
            'assembly_rules' => [
                [
                    'key' => 'party_block',
                    'description' => 'Choose company or individual wording for lender and borrower.',
                ],
                [
                    'key' => 'security_block',
                    'description' => 'Only include security definitions and clauses that match selected security types.',
                ],
                [
                    'key' => 'drawdown_block',
                    'description' => 'Include clauses 2.2 to 2.6 only if drawdown is in stages.',
                ],
                [
                    'key' => 'development_block',
                    'description' => 'Include development obligations only if loan purpose relates to property development.',
                ],
                [
                    'key' => 'company_borrower_block',
                    'description' => 'Include company-only borrower representations and schedule 1 paragraph 1 only if borrower is a company.',
                ],
                [
                    'key' => 'guarantor_schedule',
                    'description' => 'Include schedule 2 only if a personal guarantee is selected.',
                ],
                [
                    'key' => 'jurisdiction_block',
                    'description' => 'Choose exclusive or non-exclusive jurisdiction wording.',
                ],
                [
                    'key' => 'payment_block',
                    'description' => 'Include overseas payment wording only if repayments are to an overseas account.',
                ],
            ],
            'output_contract' => [
                'format' => 'html',
                'must_include_heading_numbers' => true,
                'must_preserve_legal_sequence' => true,
                'must_not_leave_placeholders' => true,
                'must_resolve_or_options' => true,
                'must_remove_drafting_notes' => true,
                'must_render_for_pdf' => true,
            ],
        ];
    }
}
