import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Check, CheckCircle2, MessageSquare, ScaleIcon, SquarePen, UserRound, X, XCircle } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { DocumentItem, DocumentStatus } from './Index';

type Props = {
    document: DocumentItem;
    onBack: () => void;
    onChangeStatus: (status: DocumentStatus) => void;
    onSaveNote: (note: string) => void;
};

function statusBadge(status: DocumentStatus) {
    switch (status) {
        case 'pending_review':
            return 'inline-flex items-center rounded-full border border-[#F6E4B5] bg-[#FFF7E6] px-3 py-1 text-xs font-medium text-[#B7791F]';
        case 'in_review':
            return 'inline-flex items-center rounded-full border border-[#C7D2FE] bg-[#EEF2FF] px-3 py-1 text-xs font-medium text-[#4F46E5]';
        case 'approved':
            return 'inline-flex items-center rounded-full border border-[#A7F3D0] bg-[#ECFDF5] px-3 py-1 text-xs font-medium text-[#059669]';
        case 'rejected':
            return 'inline-flex items-center rounded-full border border-[#FECACA] bg-[#FEF2F2] px-3 py-1 text-xs font-medium text-[#DC2626]';
        default:
            return '';
    }
}

function statusText(status: DocumentStatus) {
    switch (status) {
        case 'pending_review':
            return 'Pending Review';
        case 'in_review':
            return 'In Review';
        case 'approved':
            return 'Approved';
        case 'rejected':
            return 'Rejected';
        default:
            return status;
    }
}

function ContractSection({ title, lines = ['w-full', 'w-11/12', 'w-10/12'] }: { title: string; lines?: string[] }) {
    return (
        <section className="space-y-3">
            <h3 className="text-[13px] font-semibold tracking-[0.14em] text-[#3B332E] uppercase">{title}</h3>

            <div className="space-y-2">
                {lines.map((width, index) => (
                    <div key={`${title}-${index}`} className={`h-2 rounded-full bg-[#EFE9E0] ${width}`} />
                ))}
            </div>
        </section>
    );
}

export default function ReviewDocumentView({ document, onBack, onChangeStatus, onSaveNote }: Props) {
    const [note, setNote] = useState(document.note ?? '');
    const [decision, setDecision] = useState<'approved' | 'rejected' | null>(null);

    useEffect(() => {
        setNote(document.note ?? '');
        setDecision(null);
    }, [document.note, document.id]);

    return (
        <div className="grid grid-cols-1 gap-6 xl:grid-cols-[minmax(0,1fr)_280px]">
            <div className="space-y-4">
                <div className="flex flex-col gap-2">
                    <div className="flex flex-wrap items-center gap-3">
                        <h1 className="text-3xl font-semibold tracking-tight text-[#1A1614]">{document.title}</h1>
                        <span className={statusBadge(document.status)}>{statusText(document.status)}</span>
                    </div>

                    <p className="text-sm text-[#6B635B]">
                        Submitted: {document.submittedAtLabel} · {document.submittedBy}
                    </p>
                </div>

                <Card className="overflow-hidden rounded-2xl border-[#E7E1D7] bg-white shadow-sm">
                    <CardContent className="p-0">
                        <div className="h-[650px] overflow-y-auto bg-[#FBF8F2] p-6 md:p-8">
                            <div className="mx-auto max-w-4xl rounded-xl border border-[#ECE5DA] bg-white px-7 py-8 shadow-[0_1px_2px_rgba(26,22,20,0.04)] md:px-8 md:py-9">
                                <div className="space-y-8">
                                    <header className="space-y-2 text-center">
                                        <h2 className="font-serif text-[20px] font-bold tracking-tight text-[#221D19] md:text-[24px]">
                                            RESIDENTIAL LEASE AGREEMENT
                                        </h2>
                                        <p className="text-xs font-medium text-[#8B8178] md:text-sm">
                                            Generated by CHOROS.IO · Submitted for legal review
                                        </p>
                                    </header>

                                    <div className="space-y-7">
                                        <ContractSection title="1. PARTIES TO AGREEMENT" lines={['w-full', 'w-[86%]', 'w-[78%]']} />

                                        <ContractSection title="2. PROPERTY DETAILS" lines={['w-full', 'w-[88%]', 'w-[72%]']} />

                                        <ContractSection title="3. TERM & COMMENCEMENT" lines={['w-full', 'w-[87%]', 'w-[72%]']} />

                                        <ContractSection title="4. RENT & PAYMENT" lines={['w-full', 'w-[88%]', 'w-[72%]']} />

                                        <ContractSection title="5. DEPOSITS" lines={['w-full', 'w-[86%]', 'w-[79%]']} />

                                        <ContractSection title="6. TENANT OBLIGATIONS" lines={['w-full', 'w-[89%]', 'w-[76%]']} />

                                        <ContractSection title="7. LANDLORD OBLIGATIONS" lines={['w-full', 'w-[85%]', 'w-[74%]']} />

                                        <ContractSection title="8. TERMINATION" lines={['w-full', 'w-[83%]', 'w-[68%]']} />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            </div>

            <div className="space-y-3">
                <Card className="border-[#E7E1D7] bg-white shadow-sm">
                    <CardHeader className="px-4 pt-4 pb-2">
                        <CardTitle className="flex items-center gap-2 text-[12px] font-semibold tracking-wide text-[#4E463F] uppercase">
                            <ScaleIcon className="h-3.5 w-3.5 text-[#7C7368]" />
                            Lawyer Decision
                        </CardTitle>
                    </CardHeader>

                    <CardContent className="space-y-3 px-4 pb-4">
                        {decision === null && (
                            <>
                                <button
                                    type="button"
                                    onClick={() => {
                                        onChangeStatus('approved');
                                        setDecision('approved');
                                    }}
                                    className="flex h-10 w-full items-center justify-center gap-2 rounded-lg bg-[#1F9D6A] px-4 text-sm font-semibold text-white transition-all hover:bg-[#188657]"
                                >
                                    <Check className="h-4 w-4" />
                                    Approve Document
                                </button>

                                <button
                                    type="button"
                                    onClick={() => onChangeStatus('in_review')}
                                    className="flex h-10 w-full items-center justify-center gap-2 rounded-lg border border-[#D8D1C7] bg-white px-4 text-sm font-semibold text-[#2F2A26] transition-colors hover:bg-[#F7F3EB]"
                                >
                                    <SquarePen className="h-4 w-4" />
                                    Request Amendments
                                </button>

                                <button
                                    type="button"
                                    onClick={() => {
                                        onChangeStatus('rejected');
                                        setDecision('rejected');
                                    }}
                                    className="flex h-10 w-full items-center justify-center gap-2 rounded-lg border border-[#F3C7C7] bg-white px-4 text-sm font-semibold text-[#C45454] transition-colors hover:bg-[#FFF4F4]"
                                >
                                    <X className="h-4 w-4" />
                                    Reject
                                </button>
                            </>
                        )}

                        {decision === 'approved' && (
                            <div className="flex flex-col items-center gap-3 py-3 text-center">
                                <CheckCircle2 className="h-8 w-8 text-[#1F9D6A]" />

                                <div className="space-y-1">
                                    <p className="text-sm font-semibold text-[#1A1614]">Document Approved</p>
                                    <p className="text-xs text-[#6B635B]">The client has been notified and can now sign</p>
                                </div>

                                <button
                                    type="button"
                                    onClick={onBack}
                                    className="mt-2 w-full rounded-lg bg-[#3D2B1F] px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-[#2E2017]"
                                >
                                    Back to Dashboard
                                </button>
                            </div>
                        )}

                        {decision === 'rejected' && (
                            <div className="flex flex-col items-center gap-3 py-3 text-center">
                                <XCircle className="h-8 w-8 text-[#DC2626]" />

                                <div className="space-y-1">
                                    <p className="text-sm font-semibold text-[#1A1614]">Document Rejected</p>
                                    <p className="text-xs text-[#6B635B]">The client has been notified with your feedback</p>
                                </div>

                                <button
                                    type="button"
                                    onClick={onBack}
                                    className="mt-2 w-full rounded-lg bg-[#3D2B1F] px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-[#2E2017]"
                                >
                                    Back to Dashboard
                                </button>
                            </div>
                        )}
                    </CardContent>
                </Card>

                <Card className="border-[#E7E1D7] bg-white shadow-sm">
                    <CardHeader className="px-4 pt-4 pb-2">
                        <CardTitle className="flex items-center gap-2 text-[12px] font-semibold tracking-wide text-[#4E463F] uppercase">
                            <MessageSquare className="h-3.5 w-3.5 text-[#7C7368]" />
                            Add Note
                        </CardTitle>
                    </CardHeader>

                    <CardContent className="space-y-2 px-4 pb-4">
                        <textarea
                            value={note}
                            onChange={(e) => setNote(e.target.value)}
                            placeholder="Leave a note for the client..."
                            className="min-h-[88px] w-full rounded-lg border border-[#E7E1D7] bg-[#FCFAF6] px-3 py-2.5 text-sm text-[#1A1614] outline-none placeholder:text-[#9B938A] focus:border-[#CDBBA4]"
                        />
                        <button
                            type="button"
                            onClick={() => onSaveNote(note)}
                            className="h-9 w-full rounded-lg border border-[#D8D1C7] bg-white px-4 text-sm font-medium text-[#2F2A26] transition-all hover:bg-[#F7F3EB]"
                        >
                            Save Note
                        </button>
                    </CardContent>
                </Card>

                <Card className="border-[#E7E1D7] bg-white shadow-sm">
                    <CardHeader className="px-4 pt-4 pb-2">
                        <CardTitle className="flex items-center gap-2 text-[12px] font-semibold tracking-wide text-[#4E463F] uppercase">
                            <UserRound className="h-3.5 w-3.5 text-[#7C7368]" />
                            Client Info
                        </CardTitle>
                    </CardHeader>

                    <CardContent className="space-y-3 px-4 pb-4 text-sm">
                        <div>
                            <p className="text-[11px] text-[#8A8178]">Name</p>
                            <p className="font-medium text-[#1A1614]">{document.submittedBy}</p>
                        </div>

                        <div>
                            <p className="text-[11px] text-[#8A8178]">Email</p>
                            <p className="font-medium text-[#1A1614]">{document.clientEmail ?? '—'}</p>
                        </div>

                        <div>
                            <p className="text-[11px] text-[#8A8178]">KYC</p>
                            <p className="font-medium text-[#1A1614]">✓ {document.kycStatus ?? 'Pending'}</p>
                        </div>

                        <div>
                            <p className="text-[11px] text-[#8A8178]">Payment</p>
                            <p className="font-medium text-[#1A1614]">✓ {document.paymentStatus ?? 'Pending'}</p>
                        </div>
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
